name: Deploy Site

on:
  push:
    branches: [ "main" ] # Запускать при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build with secret
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }} # Используем секрет
        run: |
          # Пример: подставляем токен в .env файл
          echo "API_KEY=$API_TOKEN" > .env
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Путь к собранным файлам
